'use client';

import Link from 'next/link';
import { useState } from 'react';
import { ArrowLeft, ArrowUpLeft, Check, Globe2, Layers3, Menu, MonitorPlay, Moon, Palette, Sparkles, Sun, X } from 'lucide-react';
import { motion } from 'motion/react';
import { AuthMenu } from '@/components/auth/AuthMenu';
import { Preview } from '@/components/preview/Preview';
import { TemplateCatalog } from '@/components/templates/TemplateCatalog';
import { FeaturedAssets } from '@/components/assets/FeaturedAssets';
import { PriceCalculator } from '@/components/pricing/PriceCalculator';
import { useLanguage } from '@/hooks/useLanguage';
import { designFromTemplate } from '@/lib/templates';
import { palettes } from '@/lib/catalog';
import { addOnPricing, formatPrice, sitePricing, siteTypeEnglish } from '@/lib/pricing';

const extras = [
  { key: 'extraPage', ar: 'صفحة إضافية', en: 'Extra page', unitAr: 'للصفحة', unitEn: 'per page' },
  { key: 'blog', ar: 'مدونة', en: 'Blog', unitAr: 'مرة واحدة', unitEn: 'one time' },
  { key: 'booking', ar: 'نظام حجز', en: 'Booking module', unitAr: 'مرة واحدة', unitEn: 'one time' },
  { key: 'catalog', ar: 'كتالوج منتجات', en: 'Product catalog', unitAr: 'مرة واحدة', unitEn: 'one time' },
  { key: 'bilingual', ar: 'لغة ثانية', en: 'Second language', unitAr: 'مرة واحدة', unitEn: 'one time' },
  { key: 'content', ar: 'كتابة محتوى', en: 'Content writing', unitAr: 'للصفحة', unitEn: 'per page' },
  { key: 'hostingYear', ar: 'استضافة', en: 'Hosting', unitAr: 'سنويًا', unitEn: 'per year' },
  { key: 'careMonth', ar: 'صيانة ودعم', en: 'Care and support', unitAr: 'شهريًا', unitEn: 'per month' },
] as const;

export default function Home() {
  const { language, changeLanguage, en } = useLanguage();
  const [dark, setDark] = useState(false);
  const [menu, setMenu] = useState(false);
  const [heroTemplate, setHeroTemplate] = useState('market');
  const [heroPalette, setHeroPalette] = useState('luxury');
  const t = (ar: string, english: string) => en ? english : ar;
  const basePreview = designFromTemplate(heroTemplate, t('مشروعي الجديد', 'My new project'), language);
  const previewPalette = palettes.find(palette => palette.id === heroPalette) ?? palettes[0];
  const preview = basePreview ? { ...basePreview, palette: previewPalette } : null;

  return <div className={`home${dark ? ' dark' : ''}`} dir={en ? 'ltr' : 'rtl'} lang={language}>
    <header className="home-nav"><div className="home-nav-inner"><Link className="home-logo" href="/">WEB<span>CRAFT</span><i/></Link><nav className={menu ? 'open' : ''}><a href="#top" onClick={() => setMenu(false)}>{t('الرئيسية', 'Home')}</a><a href="#templates" onClick={() => setMenu(false)}>{t('القوالب', 'Templates')}</a><Link href="/library" onClick={() => setMenu(false)}>{t('مكتبة الأكواد', 'Code library')}</Link><a href="#pricing" onClick={() => setMenu(false)}>{t('الأسعار', 'Pricing')}</a><a href="#how" onClick={() => setMenu(false)}>{t('كيف يعمل؟', 'How it works')}</a></nav><div className="home-nav-actions"><AuthMenu language={language}/><button type="button" title={t('تغيير اللغة', 'Change language')} aria-label={t('التبديل إلى الإنجليزية', 'Switch to Arabic')} onClick={() => changeLanguage(en ? 'ar' : 'en')}><Globe2 size={17}/><span>{en ? 'AR' : 'EN'}</span></button><button type="button" title={t('تغيير المظهر', 'Change appearance')} aria-label={t('تغيير المظهر', 'Change appearance')} onClick={() => setDark(!dark)}>{dark ? <Sun size={18}/> : <Moon size={18}/>}</button><Link href="/builder" className="home-nav-cta">{t('ابدأ الآن', 'Start now')} <ArrowLeft size={16}/></Link><button type="button" className="home-mobile-menu" onClick={() => setMenu(!menu)} aria-label={t('القائمة', 'Menu')}>{menu ? <X size={20}/> : <Menu size={20}/>}</button></div></div></header>
    <main id="top"><section className="home-hero"><div className="hero-glow"/><div className="home-hero-inner"><motion.div initial={{ opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }} className="home-hero-copy"><div className="hero-badge"><span><Sparkles size={13}/></span>{t('كل ما يحتاجه مشروعك الرقمي، في مكان واحد', 'Everything your digital business needs, in one place')}<ArrowLeft size={13}/></div><h1>{t('من فكرة إلى', 'From idea to')}<br/><em>{t('مشروع يعمل.', 'a working business.')}</em></h1><p>{t('أنشئ موقعك بمحرر بصري، أدر محتواه من مساحة عمل واحدة، وشارك فريقك في تطويره.', 'Build your site visually, manage its content in one workspace, and collaborate with your team.')}</p><div className="home-hero-actions"><Link href="/dashboard" className="primary-cta">{t('افتح مساحة العمل', 'Open your workspace')} <ArrowLeft size={18}/></Link><a href="#how" className="secondary-cta">{t('كيف تعمل WEBCRAFT', 'How WEBCRAFT works')} <ArrowUpLeft size={17}/></a></div><div className="hero-trust"><div className="avatar-stack"><span>✦</span><span>◈</span><span>✳</span></div><div><strong>{t('كل تفصيل، باختيارك', 'Every detail is your choice')}</strong><small>{t('القوالب والألوان والمعاينة مشمولة', 'Templates, colors, and preview included')}</small></div></div></motion.div><motion.div initial={{ opacity: 0, scale: .94, y: 28 }} animate={{ opacity: 1, scale: 1, y: 0 }} transition={{ duration: .7, delay: .12 }} className="hero-demo"><div className="hero-demo-header"><div className="demo-dots"><i/><i/><i/></div><span>webcraft / live preview</span><span className="demo-live"><i/> LIVE</span></div><div className="hero-demo-body"><div className="hero-demo-side"><div className="demo-side-title"><span>◈</span> {t('تخصيص التصميم', 'Customize design')}</div><div className="demo-side-line active"><Palette size={14}/> {t('الألوان', 'Colors')} <Check size={13}/></div><div className="demo-side-line"><Layers3 size={14}/> {t('القوالب', 'Templates')}</div><div className="demo-template-switch" role="group" aria-label={t('اختيار قالب المعاينة', 'Choose preview template')}>
              {[['market', t('متجر', 'Store')], ['cafe', t('مقهى', 'Cafe')], ['folio', t('أعمال', 'Portfolio')]].map(([id, label]) => <button key={id} type="button" className={heroTemplate === id ? 'selected' : ''} onClick={() => setHeroTemplate(id)}>{label}</button>)}
            </div><div className="demo-side-bottom"><span>{t('المعاينة المباشرة', 'Live preview')}</span><b>LIVE</b><i><span/></i></div></div><div className="hero-demo-preview">{preview && <Preview design={preview} compact/>}</div></div><div className="floating-color"><span>{t('لوحة الألوان', 'Color palette')}</span><div className="hero-palette-options" role="group" aria-label={t('اختيار ألوان المعاينة', 'Choose preview colors')}>{['luxury','gold','blue','green'].map(id => { const palette = palettes.find(item => item.id === id)!; return <button key={id} type="button" aria-label={palette.name} aria-pressed={heroPalette === id} className={heroPalette === id ? 'selected' : ''} style={{ background: palette.primary }} onClick={() => setHeroPalette(id)}/> })}</div><strong>{previewPalette.name} <Check size={12}/></strong></div><div className="floating-selection"><span><Check size={14}/></span><div><strong>{t('تغييراتك تظهر فورًا', 'See changes instantly')}</strong><small>{t('معاينة تفاعلية مباشرة', 'Interactive live preview')}</small></div></div></motion.div></div><div className="home-hero-bottom"><span>{t('من الفكرة إلى تصور واضح', 'From idea to a clear plan')}</span><div><span>{t('01 / استكشف', '01 / Explore')}</span><i/><span>{t('02 / خصّص', '02 / Customize')}</span><i/><span>{t('03 / شاهد', '03 / Preview')}</span><i/><span>{t('04 / أرسل', '04 / Send')}</span></div></div></section>

    <section className="features-section" id="features"><div className="section-label"><span/> {t('كل ما تحتاجه لتبدأ', 'Everything you need to begin')}</div><div className="features-heading"><h2>{t('موقعك يبدأ', 'Your website starts')} <em>{t('من هنا.', 'here.')}</em></h2><p>{t('من القالب إلى المعاينة، اصنع تصورًا واضحًا قبل قرار التنفيذ.', 'From template to preview, shape a clear plan before building.')}</p></div><div className="feature-cards"><article><div className="feature-icon"><Palette size={23}/></div><span>01</span><h3>{t('هوية تشبهك', 'Your visual identity')}</h3><p>{t('جرّب الألوان والخطوط حتى تصل إلى مزيج يعبّر عن مشروعك.', 'Try colors and type until the design feels like your brand.')}</p><div className="feature-art palette-art"><i/><i/><i/><i/></div></article><article><div className="feature-icon"><Layers3 size={23}/></div><span>02</span><h3>{t('قوالب قابلة للتخصيص', 'Flexible templates')}</h3><p>{t('ابدأ بتصميم متكامل، ثم عدّل ترتيب الأقسام ومحتواها.', 'Start with a complete design, then edit sections and content.')}</p><div className="feature-art layers-art"><i/><i/><i/></div></article><article><div className="feature-icon"><MonitorPlay size={23}/></div><span>03</span><h3>{t('سعر أوضح', 'Clearer pricing')}</h3><p>{t('راجع سعر القالب والإضافات قبل إرسال طلب التنفيذ.', 'Review the template and add-on estimate before sending a request.')}</p><div className="feature-art preview-art"><i/><i/><i/></div></article></div></section>

    <section className="templates-section" id="templates"><div className="section-label"><span/> {t('كتالوج القوالب', 'Template catalog')}</div><div className="templates-intro"><div><h2>{t('اختر نقطة البداية.', 'Choose your starting point.')}</h2><p>{t('ستة قوالب جاهزة تُطبّق على مشروعك عند إنشائه، ولكل قالب سعر ابتدائي واضح.', 'Six ready-made templates you can apply when creating a project, each with a clear starting price.')}</p></div><Link href="/builder">{t('كل القوالب', 'All templates')} <ArrowLeft size={17}/></Link></div><TemplateCatalog language={language}/></section>

    <FeaturedAssets language={language}/>

    <section className="pricing-section" id="pricing"><div className="section-label"><span/> {t('الأسعار التقديرية', 'Indicative pricing')}</div><div className="pricing-intro"><h2>{t('اعرف تكلفة', 'Know the cost')} <em>{t('البداية.', 'up front.')}</em></h2><p>{t('كل سعر أساسي يشمل تصميمًا متجاوبًا وقالبًا قابلًا للتخصيص وصفحات بعدد الخطة. اختيار الألوان والخطوط والتنسيقات والمعاينة دون رسوم إضافية.', 'Each base price includes a responsive, customizable template and the listed number of pages. Colors, fonts, layouts, and preview carry no extra charge.')}</p></div><div className="price-list">{Object.entries(sitePricing).map(([siteType, details]) => <div key={siteType}><span>{en ? siteTypeEnglish[siteType as keyof typeof sitePricing] : siteType}</span><small>{details.pages} {en ? details.pages === 1 ? 'page included' : 'pages included' : details.pages === 1 ? 'صفحة مشمولة' : 'صفحات مشمولة'}</small><strong dir="ltr">{formatPrice(details.price, language)}</strong></div>)}</div><h3 className="pricing-subtitle">{t('الإضافات والخدمات', 'Add-ons and services')}</h3><div className="addon-list">{extras.map(extra => <div key={extra.key}><span>{en ? extra.en : extra.ar}</span><small>{en ? extra.unitEn : extra.unitAr}</small><strong dir="ltr">{formatPrice(addOnPricing[extra.key], language)}</strong></div>)}</div><PriceCalculator language={language}/><p className="pricing-note">{t('الأسعار تقديرية، وليست دفعًا إلكترونيًا أو عرضًا نهائيًا. تُراجع التفاصيل والضرائب ورسوم النطاق في عرض مكتوب قبل التنفيذ.', 'These are estimates, not an online checkout or a final quote. Scope, taxes, and domain fees are confirmed in a written proposal before work begins.')}</p></section>

    <section className="how-section" id="how"><div className="section-label"><span/> {t('كيف يعمل؟', 'How it works')}</div><h2>{t('أربع خطوات،', 'Four steps,')} <em>{t('وتبدأ الحكاية.', 'one clear path.')}</em></h2><div className="how-grid">{[
      ['01', t('اختر قالبًا', 'Pick a template'), t('اختر الشكل الأقرب لطبيعة مشروعك وسعرك المبدئي.', 'Find the right look and starting price for your project.')],
      ['02', t('اصنع هويتك', 'Shape your identity'), t('غيّر الألوان والخطوط والنصوص والأقسام.', 'Adjust colors, type, copy, and sections.')],
      ['03', t('راجع السعر', 'Review the estimate'), t('تظهر الإضافات وسعرها في ملخص مشروعك.', 'See add-ons and their prices in your project summary.')],
      ['04', t('أرسل تصورك', 'Send your idea'), t('شارك التفاصيل لنراجع النطاق قبل التنفيذ.', 'Share the details so the scope can be reviewed.')],
    ].map(([number, title, body]) => <article key={number}><span>{number}</span><div className="how-line"/><h3>{title}</h3><p>{body}</p></article>)}</div></section>

    <section className="account-section" id="account"><div className="section-label"><span/> {t('مساحة العمل', 'Workspace')}</div><h2>{t('كل مشروع في', 'Every project')} <em>{t('مكانه.', 'in one place.')}</em></h2><p>{t('أنشئ حسابك لتجمع تصاميمك في مساحة واحدة. افتح مشروعًا محفوظًا، وأضف متعاونين للتعديل معك.', 'Create an account to keep your designs together, reopen saved projects, and invite collaborators.')}</p><div className="account-grid"><article><strong>01</strong><h3>{t('احفظ فكرتك', 'Save your idea')}</h3><p>{t('عد إلى التصميم وأكمل التعديل في أي وقت.', 'Return and keep editing whenever you are ready.')}</p></article><article><strong>02</strong><h3>{t('اعملوا معًا', 'Work together')}</h3><p>{t('أضف مستخدمين لديهم حسابات مؤكدة ليشاركوك التحرير.', 'Invite verified users to collaborate on the design.')}</p></article><article><strong>03</strong><h3>{t('راجع قبل الإرسال', 'Review before sending')}</h3><p>{t('شاهد المعاينة وتفصيل السعر قبل طلب التنفيذ.', 'See the preview and price breakdown before requesting a build.')}</p></article></div><Link className="account-link" href="/signup">{t('أنشئ حسابًا وابدأ', 'Create an account')} <ArrowLeft size={17}/></Link></section>

    <section className="home-cta"><div className="cta-orb one"/><div className="cta-orb two"/><div className="section-label">{t('مساحتك الإبداعية بانتظارك', 'Your creative space awaits')}</div><h2>{t('جاهز لترى فكرتك', 'Ready to see your idea')}<br/><em>{t('تأخذ شكلًا حقيقيًا؟', 'take shape?')}</em></h2><p>{t('اختر قالبًا وابدأ تخصيصه، ثم راجع السعر في الملخص.', 'Choose a template, make it yours, and review the price in the summary.')}</p><Link href="/builder">{t('ابدأ تصميم موقعك', 'Start designing')} <ArrowLeft size={18}/></Link></section></main>

    <footer className="home-footer"><div><Link className="home-logo" href="/">WEB<span>CRAFT</span><i/></Link><p>{t('من فكرتك إلى تجربة رقمية تستحق أن تُرى.', 'From your idea to a digital experience worth seeing.')}</p></div><nav><a href="#top">{t('الرئيسية', 'Home')}</a><a href="#templates">{t('القوالب', 'Templates')}</a><a href="#pricing">{t('الأسعار', 'Pricing')}</a><a href="#how">{t('كيف يعمل؟', 'How it works')}</a></nav><span>© 2026 WEBCRAFT. {t('جميع الحقوق محفوظة.', 'All rights reserved.')}</span></footer>
  </div>;
}
