import { NextResponse } from 'next/server';
import { z } from 'zod';
import { serviceDb, verifyAdmin } from '@/lib/supabase/server';
import { JsonBodyError, readJsonLimited } from '@/lib/server/json';
export const runtime='nodejs';
const short=z.string().trim().min(1).max(160),hex=z.string().regex(/^#[0-9a-fA-F]{6}$/);
const component=z.object({id:z.string().regex(/^[a-z0-9-]{3,80}$/),category:z.enum(['nav','hero','footer','section']),kind:short,name:short,description:z.string().max(500),variant:z.number().int().min(0).max(29),title:z.string().max(160),body:z.string().max(1000),visible:z.boolean(),order:z.number().int().min(0).max(1000),group:short}).strict();
const palette=z.object({id:z.string().regex(/^[a-z0-9-]{3,80}$/),name:short,primary:hex,secondary:hex,accent:hex,background:hex,text:hex,visible:z.boolean(),order:z.number().int().min(0).max(1000)}).strict();
export async function GET(req:Request){const db=serviceDb();if(!db)return NextResponse.json({components:[],palettes:[],demo:true});const admin=await verifyAdmin(req);const [c,p]=await Promise.all([db.from('catalog_components').select('data'),db.from('color_palettes').select('data')]);if(c.error||p.error)return NextResponse.json({error:'تعذر تحميل الكتالوج'},{status:503});const publicValue=(d:Record<string,unknown>)=>admin||d.visible?d:{id:d.id,category:d.category,visible:false};return NextResponse.json({components:(c.data||[]).map(row=>publicValue(row.data)),palettes:(p.data||[]).map(row=>publicValue(row.data))})}
export async function PUT(req:Request){const db=serviceDb();if(!db)return NextResponse.json({error:'Supabase غير مهيأ'},{status:503});if(!await verifyAdmin(req))return NextResponse.json({error:'غير مصرح'},{status:403});let body:unknown;try{body=await readJsonLimited(req,10000)}catch(caught){const error=caught as JsonBodyError;return NextResponse.json({error:error.message},{status:error.status||400})}const raw=body as {collection?:string;data?:unknown};if(raw?.collection!=='component'&&raw?.collection!=='palette')return NextResponse.json({error:'مجموعة غير صالحة'},{status:400});const parsed=(raw.collection==='component'?component:palette).safeParse(raw.data);if(!parsed.success)return NextResponse.json({error:'بيانات القالب غير صالحة'},{status:400});const table=raw.collection==='component'?'catalog_components':'color_palettes';const {error}=await db.from(table).upsert({id:parsed.data.id,data:parsed.data});if(error)return NextResponse.json({error:'تعذر حفظ القالب'},{status:500});return NextResponse.json({ok:true})}
