import { createClient } from '@supabase/supabase-js';

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_SECRET_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) throw Error('Supabase server settings are missing.');
const db = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });

const assets = [
  {
    id: 'asset-nova-landing', category: 'template', framework: 'html', title: 'قالب نوفا للأعمال', titleEn: 'Nova business landing',
    description: 'صفحة افتتاحية أنيقة لمشروعك مع دعوة واضحة للتواصل.', descriptionEn: 'A polished business landing page with a clear call to action.', price: 120, published: true,
    html: '<main class="nova"><nav><b>NOVA<span>✦</span></b><a href="#contact">تواصل معنا</a></nav><section><small>تجربة رقمية تليق بفكرتك</small><h1>نصنع حضورك<br><em>بشكل مختلف.</em></h1><p>مساحة أنيقة لعرض خدماتك وتحويل الزوار إلى عملاء.</p><a class="cta" href="#contact">ابدأ مشروعك ←</a></section><footer id="contact">NOVA STUDIO · 2026</footer></main>',
    css: '.nova{min-height:100vh;background:#16142a;color:#fff;direction:rtl;padding:24px 6%;position:relative;overflow:hidden}.nova:before{content:"";position:absolute;width:380px;height:380px;border-radius:50%;background:#7448df;filter:blur(110px);top:4%;left:0;opacity:.6}.nova nav,.nova section,.nova footer{position:relative}.nova nav{display:flex;justify-content:space-between;align-items:center}.nova nav b{font-size:22px}.nova nav b span{color:#a084ff}.nova nav a{color:#dcd5f4;text-decoration:none;font-size:13px}.nova section{padding:70px 0 65px;max-width:600px}.nova small{color:#b7a1ff;letter-spacing:.1em}.nova h1{font-size:clamp(34px,5vw,66px);line-height:1.15;margin:18px 0}.nova h1 em{color:#b59bff;font-style:normal}.nova p{color:#c6bedb;line-height:1.8}.nova .cta{display:inline-block;margin-top:18px;padding:13px 22px;border-radius:10px;background:#9a73fc;color:white;text-decoration:none;font-weight:700}.nova footer{border-top:1px solid #5a536f;color:#978da9;padding-top:16px;font-size:11px}', js: '', nextCode: '',
  },
  {
    id: 'asset-orbit-button', category: 'button', framework: 'html', title: 'زر أوربت المتوهج', titleEn: 'Orbit glow button',
    description: 'زر تفاعلي متدرج مع تأثير ضوئي وحركة خفيفة.', descriptionEn: 'A gradient action button with a glow and subtle motion.', price: 8, published: true,
    html: '<div class="stage"><button class="orbit" type="button"><span>اكتشف المزيد</span><span aria-hidden="true">↗</span></button></div>',
    css: '.stage{min-height:100vh;display:grid;place-items:center;background:#eee9ff}.orbit{border:1px solid #ccb2ff;background:linear-gradient(120deg,#713fe0,#a26aff);color:#fff;padding:17px 24px;border-radius:16px;font:bold 20px system-ui;display:flex;align-items:center;gap:28px;cursor:pointer;box-shadow:0 14px 30px #784bd765;transition:transform .25s,box-shadow .25s}.orbit:hover{transform:translateY(-5px);box-shadow:0 20px 42px #784bd795}.orbit:active{transform:translateY(1px)}.orbit span:last-child{font-size:26px}', js: '', nextCode: '',
  },
  {
    id: 'asset-pricing-card', category: 'component', framework: 'html', title: 'بطاقة تسعير تفاعلية', titleEn: 'Interactive pricing card',
    description: 'بطاقة سعر منظمة مع مزايا واضحة وزر تواصل.', descriptionEn: 'A clean price card with benefits and a contact action.', price: 25, published: true,
    html: '<div class="wrap"><article class="plan"><div class="head"><span>الخطة المميزة</span><b>✦</b></div><h2>كل ما تحتاجه لتبدأ</h2><p>تصميم متجاوب، صفحات أساسية، ومعاينة قبل التنفيذ.</p><div class="price">٢٥ <small>ر.ع / بداية من</small></div><ul><li>✓ تصميم مخصص</li><li>✓ متوافق مع الهاتف</li><li>✓ تحديثات المحتوى</li></ul><button type="button">اختر هذه الخطة ←</button></article></div>',
    css: '.wrap{background:#f5f3fa;min-height:100vh;display:grid;place-items:center;direction:rtl;padding:20px}.plan{background:#fff;border:1px solid #e8e2f2;box-shadow:0 25px 50px #34275c1a;padding:30px;border-radius:24px;max-width:390px;width:100%;color:#282333}.head{display:flex;justify-content:space-between;color:#7b55db;font-weight:800}.head b{font-size:28px}.plan h2{font-size:25px;margin:12px 0}.plan p{color:#756b80;line-height:1.7}.price{font-size:40px;color:#7b55db;font-weight:900;margin:15px 0}.price small{font-size:13px;color:#8a8095}.plan ul{list-style:none;padding:0;line-height:2.3;color:#4b4256}.plan button{width:100%;padding:14px;border:0;border-radius:12px;background:#7b55db;color:white;font-weight:800;cursor:pointer}', js: '', nextCode: '',
  },
  {
    id: 'asset-faq-accordion', category: 'script', framework: 'html', title: 'أسئلة شائعة قابلة للفتح', titleEn: 'FAQ accordion',
    description: 'قسم أسئلة شائعة يعمل بـ JavaScript بسيط.', descriptionEn: 'An accessible FAQ block powered by a tiny JavaScript snippet.', price: 15, published: true,
    html: '<main class="faq"><h2>أسئلة شائعة</h2><button type="button" aria-expanded="false">كم يستغرق تنفيذ الموقع؟ <span>+</span></button><p hidden>يعتمد على حجم المشروع، وعادة يبدأ من أسبوعين.</p><button type="button" aria-expanded="false">هل يمكن تعديل التصميم؟ <span>+</span></button><p hidden>نعم، يمكنك مراجعة التصميم قبل اعتماده.</p></main>',
    css: '.faq{min-height:100vh;background:#f8f5ff;padding:38px;direction:rtl;color:#29203e}.faq h2{font-size:30px}.faq button{width:100%;display:flex;justify-content:space-between;align-items:center;background:white;border:1px solid #e8defb;padding:17px;border-radius:12px;margin-top:10px;font:700 17px system-ui;color:#382c50;cursor:pointer}.faq button span{color:#8b62ed}.faq p{background:#fff;margin:0;padding:17px;color:#756a83;border-radius:0 0 12px 12px}',
    js: 'document.querySelectorAll(".faq button").forEach(button => { button.addEventListener("click", () => { const open = button.getAttribute("aria-expanded") === "true"; button.setAttribute("aria-expanded", String(!open)); button.nextElementSibling.hidden = open; button.querySelector("span").textContent = open ? "+" : "−"; }); });', nextCode: '',
  },
  {
    id: 'asset-next-portfolio', category: 'template', framework: 'nextjs', title: 'واجهة ملف أعمال Next.js', titleEn: 'Next.js portfolio hero',
    description: 'مكوّن React / Next.js لواجهة ملف أعمال مع معاينة HTML مستقلة.', descriptionEn: 'A React / Next.js portfolio hero with an independent HTML preview.', price: 60, published: true,
    html: '<main class="portfolio"><nav><b>AMIR<span>.</span></b><small>الأعمال · عني · تواصل</small></nav><div class="hero"><span>مصمم ومطور واجهات</span><h1>أحوّل الأفكار إلى<br><em>تجارب رقمية.</em></h1><p>أبني مواقع سريعة وواضحة تستحق أن يتذكرها الناس.</p><a href="#work">شاهد أعمالي ↗</a></div><div class="work" id="work">مشاريع مختارة <span>01 / 03</span></div></main>',
    css: '.portfolio{min-height:100vh;background:#ece8e1;color:#222;direction:rtl;padding:24px 6%}.portfolio nav{display:flex;justify-content:space-between}.portfolio nav b{font-size:24px}.portfolio nav b span{color:#d55433}.portfolio nav small{color:#635f5b}.hero{padding:75px 0 65px}.hero>span{color:#c95335;font-weight:700}.hero h1{font-size:clamp(34px,5vw,64px);line-height:1.13;letter-spacing:-.02em;margin:15px 0}.hero em{font-style:normal;color:#d55433}.hero p{color:#5e5954}.hero a{display:inline-block;margin-top:12px;color:#fff;background:#252424;border-radius:100px;padding:13px 22px;text-decoration:none}.work{border-top:1px solid #b5ada5;padding-top:15px;display:flex;justify-content:space-between}.work span{color:#8d8379}', js: '',
    nextCode: `import Link from 'next/link';

export default function PortfolioHero() {
  return (
    <main className="portfolio">
      <nav><strong>AMIR.</strong><span>الأعمال · عني · تواصل</span></nav>
      <section>
        <p>مصمم ومطور واجهات</p>
        <h1>أحوّل الأفكار إلى <em>تجارب رقمية.</em></h1>
        <p>أبني مواقع سريعة وواضحة تستحق أن يتذكرها الناس.</p>
        <Link href="#work">شاهد أعمالي ↗</Link>
      </section>
    </main>
  );
}
// Add the styles from the CSS tab to your global CSS file.`,
  },
  {
    id: 'asset-sahab-store', category: 'template', framework: 'html', title: 'قالب متجر سحاب', titleEn: 'Sahab storefront',
    description: 'واجهة متجر عربية متجاوبة مع منتجات مختارة وأزرار واضحة.', descriptionEn: 'A responsive Arabic storefront with curated products and clear actions.', price: 95, published: true,
    html: '<main class="sahab"><nav><b>سَحاب<span>●</span></b><a href="#products">المتجر</a><a href="#about">قصتنا</a><button type="button" aria-label="سلة المشتريات">السلة <i>٢</i></button></nav><section class="sahab-hero"><div><small>اختيارات تصنع يومك</small><h1>تفاصيل صغيرة،<br><em>فرق كبير.</em></h1><p>منتجات مختارة بعناية لتضيف لمسة هادئة إلى يومك.</p><a href="#products">تسوق المجموعة ←</a></div><div class="sahab-art"><span>NEW<br>COLLECTION</span><b>SAHAB</b></div></section><section id="products" class="sahab-products"><header><h2>الأكثر طلبًا</h2><a href="#products">كل المنتجات ↗</a></header><div><article><i class="product-art clay">✿</i><b>مزهرية رملية</b><small>١٨ ر.ع</small></article><article><i class="product-art olive">◒</i><b>مصباح المساء</b><small>٣٢ ر.ع</small></article><article><i class="product-art rose">✧</i><b>طقم ضيافة</b><small>٢٤ ر.ع</small></article></div></section><footer id="about">سَحاب · أشياء جميلة تعيش معك</footer></main>',
    css: '.sahab{min-height:100vh;background:#f7f4ee;color:#263b36;padding:20px 6%;direction:rtl;font-family:system-ui,sans-serif}.sahab nav{display:flex;align-items:center;gap:24px;border-bottom:1px solid #dedbd1;padding-bottom:15px}.sahab nav b{font-size:24px;margin-inline-end:auto}.sahab nav b span{color:#b36e50;margin-right:5px;font-size:12px}.sahab nav a{color:#4b625a;text-decoration:none;font-size:13px}.sahab nav button{border:1px solid #d8d3c8;border-radius:99px;background:transparent;padding:9px 14px;color:#263b36}.sahab nav i{font-style:normal;background:#c27a5b;color:#fff;border-radius:99px;padding:2px 6px}.sahab-hero{display:grid;grid-template-columns:1.1fr .9fr;align-items:center;gap:30px;padding:52px 0}.sahab-hero small{color:#b66d4e;font-weight:800}.sahab-hero h1{font-size:clamp(35px,6vw,66px);line-height:1.15;margin:13px 0}.sahab-hero em{font-style:normal;color:#b66d4e}.sahab-hero p{color:#718078;line-height:1.9}.sahab-hero a{display:inline-block;background:#294c42;color:#fff;padding:12px 18px;border-radius:9px;text-decoration:none;margin-top:12px}.sahab-art{min-height:250px;border-radius:140px 140px 14px 14px;background:linear-gradient(150deg,#d9cbb5,#aec3b1);display:grid;place-items:center;position:relative;overflow:hidden;color:#294c42}.sahab-art:before{content:"";position:absolute;width:170px;height:170px;border-radius:50%;background:#f3e8d6;top:48px;left:22%}.sahab-art span{position:absolute;top:22px;right:24px;font-size:10px;letter-spacing:.15em}.sahab-art b{z-index:1;font-size:28px;letter-spacing:.3em}.sahab-products header{display:flex;align-items:center;justify-content:space-between}.sahab-products h2{font-size:25px}.sahab-products header a{color:#b66d4e;text-decoration:none}.sahab-products>div{display:grid;grid-template-columns:repeat(3,1fr);gap:13px}.sahab-products article{display:grid;gap:7px}.product-art{height:130px;border-radius:14px;display:grid;place-items:center;font-style:normal;font-size:54px}.clay{background:#eadbd1;color:#a6674d}.olive{background:#dce4d7;color:#55725c}.rose{background:#ece2e8;color:#986c86}.sahab-products article small{color:#b66d4e}.sahab footer{border-top:1px solid #dedbd1;margin-top:28px;padding-top:15px;color:#76817b;font-size:12px}@media(max-width:600px){.sahab nav{gap:11px}.sahab nav a{font-size:11px}.sahab-hero{grid-template-columns:1fr;padding:35px 0}.sahab-art{min-height:190px}.sahab-products>div{grid-template-columns:1fr 1fr}}', js: '', nextCode: '',
  },
  {
    id: 'asset-madar-saas', category: 'template', framework: 'nextjs', title: 'قالب مدار للمنصات', titleEn: 'Madar SaaS landing',
    description: 'صفحة منصة رقمية بخدمات ومؤشرات وزر بدء واضح.', descriptionEn: 'A product landing page with feature cards, metrics and a clear start action.', price: 110, published: true,
    html: '<main class="madar"><nav><b>مدار<span>✦</span></b><a href="#features">المزايا</a><a href="#plans">الأسعار</a><button>ابدأ الآن ↗</button></nav><section class="madar-hero"><small>مساحة عملك، بصورة أوضح</small><h1>اجمع شغلك<br><em>في مكان واحد.</em></h1><p>خطط لمشاريعك، تابع فريقك، واحتفظ بكل التفاصيل في لوحة سهلة.</p><button>جرّب مدار مجانًا <span>←</span></button><div class="madar-stats"><div><b>١٢+</b><small>مشروعًا نشطًا</small></div><div><b>٩٨٪</b><small>وضوح في المهام</small></div><div><b>٤.٩</b><small>تقييم المستخدمين</small></div></div></section><section id="features" class="madar-features"><article><i>◈</i><b>مساحة مرتبة</b><small>كل مشروع وفريق في واجهة واحدة.</small></article><article><i>↗</i><b>تقدم واضح</b><small>اعرف ما أُنجز وما يحتاج متابعة.</small></article><article><i>✧</i><b>تعاون أسرع</b><small>شارك المهام والملفات بسهولة.</small></article></section></main>',
    css: '.madar{min-height:100vh;background:#101624;color:#f4f4fa;direction:rtl;padding:20px 7%;font-family:system-ui,sans-serif}.madar nav{display:flex;align-items:center;gap:25px}.madar nav b{font-size:23px;margin-inline-end:auto}.madar nav b span{color:#9d83ff;margin-right:6px}.madar nav a{color:#bdc1d0;text-decoration:none;font-size:13px}.madar button{background:#9174fa;color:#fff;border:0;border-radius:9px;padding:11px 15px;font:700 13px system-ui;cursor:pointer}.madar-hero{padding:55px 0 25px;max-width:690px}.madar-hero>small{color:#a58cff;font-weight:800}.madar-hero h1{font-size:clamp(40px,6vw,70px);line-height:1.16;margin:13px 0}.madar-hero h1 em{font-style:normal;color:#a58cff}.madar-hero p{color:#aeb4c3;line-height:1.9;max-width:510px}.madar-hero button{margin-top:12px}.madar-hero button span{margin-right:12px}.madar-stats{display:flex;gap:42px;margin-top:35px;padding-top:20px;border-top:1px solid #2e3544}.madar-stats div{display:grid;gap:5px}.madar-stats b{font-size:21px}.madar-stats small{color:#939bad;font-size:11px}.madar-features{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:18px 0}.madar-features article{display:grid;gap:10px;background:#191f2d;border:1px solid #2d3443;border-radius:14px;padding:18px}.madar-features i{color:#a58cff;font-style:normal;font-size:21px}.madar-features small{color:#aeb4c3;line-height:1.6}@media(max-width:600px){.madar nav{gap:12px}.madar nav a{display:none}.madar-hero{padding-top:40px}.madar-stats{gap:16px;justify-content:space-between}.madar-features{grid-template-columns:1fr}}', js: '',
    nextCode: `import Link from 'next/link';

export default function MadarLanding() {
  return <main className="madar" dir="rtl">
    <nav><strong>مدار ✦</strong><Link href="#features">المزايا</Link><Link href="#plans">الأسعار</Link><Link href="/signup">ابدأ الآن ↗</Link></nav>
    <section className="madar-hero"><small>مساحة عملك، بصورة أوضح</small><h1>اجمع شغلك <em>في مكان واحد.</em></h1><p>خطط لمشاريعك، تابع فريقك، واحتفظ بكل التفاصيل في لوحة سهلة.</p><Link className="madar-cta" href="/signup">جرّب مدار مجانًا ←</Link></section>
    <section id="features" className="madar-features"><article>مساحة مرتبة</article><article>تقدم واضح</article><article>تعاون أسرع</article></section>
  </main>;
}
// Add the styles from the CSS tab to your global CSS file.`,
  },
  {
    id: 'asset-annual-toggle', category: 'script', framework: 'html', title: 'تبديل أسعار الخطط', titleEn: 'Billing period toggle',
    description: 'مكوّن أسعار يحوّل بين الفوترة الشهرية والسنوية.', descriptionEn: 'A pricing selector that switches between monthly and annual billing.', price: 12, published: true,
    html: '<section class="billing"><div class="billing-head"><small>خطط بسيطة</small><h2>اختر ما يناسب فريقك</h2><button id="billingToggle" type="button" aria-pressed="false"><span>شهري</span><i></i><span>سنوي · وفر ٢٠٪</span></button></div><article><b>أساسي</b><p>للبداية وتنظيم العمل</p><strong data-month="٥ ر.ع" data-year="٤ ر.ع">٥ ر.ع <small>/ شهر</small></strong><button type="button">ابدأ الآن</button></article></section>',
    css: '.billing{min-height:100vh;background:#f6f4fb;color:#2b2638;padding:28px;direction:rtl;font-family:system-ui,sans-serif;display:grid;place-content:center;gap:20px}.billing-head{text-align:center}.billing-head>small{color:#805de6;font-weight:800}.billing h2{margin:7px}.billing-head>button{display:flex;align-items:center;gap:9px;margin:15px auto;border:0;background:#fff;border-radius:99px;padding:8px 13px;color:#655d72;cursor:pointer}.billing-head i{width:34px;height:18px;border-radius:99px;background:#ddd5f1;position:relative}.billing-head i:after{content:"";position:absolute;width:14px;height:14px;background:#805de6;border-radius:50%;top:2px;right:2px;transition:.2s}.billing-head button[aria-pressed="true"] i:after{right:18px}.billing article{width:min(340px,86vw);background:white;border:1px solid #e8e2f2;border-radius:20px;padding:24px;box-shadow:0 18px 45px #2d1f5010;display:grid;gap:12px}.billing article>p{margin:0;color:#82798e}.billing article>strong{font-size:37px;color:#805de6}.billing article small{font-size:13px;color:#80788e}.billing article>button{border:0;border-radius:10px;padding:12px;background:#805de6;color:white;font-weight:800;cursor:pointer}',
    js: 'const toggle = document.querySelector("#billingToggle"); const price = document.querySelector(".billing article strong"); toggle.addEventListener("click", () => { const annual = toggle.getAttribute("aria-pressed") !== "true"; toggle.setAttribute("aria-pressed", String(annual)); price.innerHTML = `${annual ? price.dataset.year : price.dataset.month} <small>/ شهر</small>`; });', nextCode: '',
  },
  {
    id: 'asset-profile-card', category: 'component', framework: 'html', title: 'بطاقة ملف المطور', titleEn: 'Developer profile card',
    description: 'بطاقة تعريف للمطور مع المهارات وحالة التوفر.', descriptionEn: 'A developer profile card with skills and availability.', price: 18, published: true,
    html: '<article class="dev-card"><div class="dev-top"><span>متاح لمشاريع جديدة</span><b>◉</b></div><div class="dev-avatar">م</div><h2>محمد السالمي</h2><p>مطور واجهات · مسقط، عُمان</p><div class="dev-skills"><span>React</span><span>Next.js</span><span>تصميم UI</span></div><a href="mailto:hello@example.com">تواصل معي ↗</a></article>',
    css: '.dev-card{min-height:100vh;display:grid;align-content:center;justify-items:center;gap:12px;background:#f4f2f8;color:#292536;padding:24px;direction:rtl;font-family:system-ui,sans-serif}.dev-card>*{margin:0}.dev-top{width:min(370px,90vw);display:flex;justify-content:space-between;color:#31815b;font-size:12px;font-weight:800}.dev-top b{color:#805de6}.dev-avatar{width:82px;height:82px;border-radius:24px;background:linear-gradient(145deg,#d9d0f7,#9b7bea);display:grid;place-items:center;color:#fff;font-size:35px;font-weight:900}.dev-card h2{font-size:25px}.dev-card>p{color:#777084}.dev-skills{display:flex;gap:7px;flex-wrap:wrap;justify-content:center;margin:5px}.dev-skills span{background:#fff;border:1px solid #e6e1ed;border-radius:99px;padding:7px 11px;font-size:12px;color:#655b77}.dev-card>a{margin-top:8px;padding:12px 18px;background:#805de6;color:#fff;text-decoration:none;border-radius:10px;font-weight:800}', js: '', nextCode: '',
  },
];

const rows = assets.map(data => ({ id: data.id, data }));
const { error } = await db.from('catalog_components').upsert(rows, { onConflict: 'id', ignoreDuplicates: true });
if (error) throw error;
console.log(`Seeded or preserved ${rows.length} code library items.`);
