'use client';
import { useState } from 'react';
import { ArrowLeft, Menu } from 'lucide-react';
import type { Design, Section } from '@/types/design';
import { SectionContent } from './SectionContent';
import { navNames, footerNames, sectionKindEnglish } from '@/lib/catalog';
import { siteTypeEnglish } from '@/lib/pricing';

export const demoImages = [
 '/preview/store-hero.svg',
 '/preview/product-one.svg',
 '/preview/product-two.svg',
 '/preview/product-three.svg'
];
const siteImages:Record<string,string>={
 'متجر إلكتروني':demoImages[0],
 'موقع شركة':demoImages[2],
 'موقع شخصي':demoImages[1],
 'مطعم أو كوفي':demoImages[3],
 'عيادة طبية':demoImages[2],
 'موقع حجوزات':demoImages[3],
 'منصة تعليمية':demoImages[1],
 'عقارات':demoImages[3],
 'خدمات':demoImages[2],
 'Landing Page':demoImages[2],
 'موقع مخصص':demoImages[3]
};
function Nav({d,editable,onEdit}:{d:Design;editable:boolean;onEdit?:(field:string,value:string)=>void}) {
  const [open,setOpen]=useState(false);const n=d.navbar;const en=d.locale==='en';const settings=d.navbarSettings;
  return <header className={`sample-nav nav-${n} ${settings.sticky?'nav-sticky':''} ${settings.transparent?'nav-transparent':''}`} data-name={navNames[n]}><div className="sample-nav-inner"><button className="sample-menu" onClick={()=>setOpen(!open)} aria-label={en?'Menu':'القائمة'}><Menu size={17}/></button><strong contentEditable={editable} suppressContentEditableWarning onBlur={e=>onEdit?.('projectName',e.currentTarget.textContent?.replace(/\.$/,'')||'')}>{d.logoImage&&<img className="sample-logo-image" src={d.logoImage} alt=""/>}{d.projectName || (en?'Your brand':'اسم مشروعك')}<span className="brand-dot">.</span></strong><nav className={open?'open':''}>{d.pages.slice(0,6).map((page,i)=><a key={`${page}-${i}`} href={i===0?'#preview-about':i===d.pages.length-1?'#preview-contact':'#preview-services'} contentEditable={editable} suppressContentEditableWarning onBlur={e=>{const pages=[...d.pages];pages[i]=e.currentTarget.textContent||page;onEdit?.(`page:${i}`,pages[i])}}>{page}</a>)}</nav>{settings.showLanguageSwitcher&&<button type="button" className="sample-language-switch" onClick={()=>onEdit?.('locale',en?'ar':'en')}>{en?'العربية':'EN'}</button>}{settings.showCta&&<a className="sample-nav-cta" href="#preview-contact" contentEditable={editable} suppressContentEditableWarning onBlur={e=>onEdit?.('navCta',e.currentTarget.textContent||'')}>{d.navCta|| (en?'Contact us':'تواصل معنا')} <ArrowLeft size={13}/></a>}</div></header>
}
function Hero({d,editable,onEdit}:{d:Design;editable:boolean;onEdit?:(field:string,value:string)=>void}) {const h=d.hero;const en=d.locale==='en';const image=d.heroImage||siteImages[d.siteType]||demoImages[h%demoImages.length];return <section className={`sample-hero hero-${h}`}><div className="sample-hero-copy"><div className="sample-eyebrow"><span/> {en?(siteTypeEnglish[d.siteType as keyof typeof siteTypeEnglish]||d.siteType):d.siteType} • {en?'A distinct experience':'تجربة استثنائية'}</div><h1 contentEditable={editable} suppressContentEditableWarning onBlur={e=>onEdit?.('heroTitle',e.currentTarget.textContent||'')}>{d.heroTitle}</h1><p contentEditable={editable} suppressContentEditableWarning onBlur={e=>onEdit?.('heroBody',e.currentTarget.textContent||'')}>{d.heroBody}</p><div className="sample-actions"><a className={`sample-button button-${d.buttonStyle}`} href="#preview-services" contentEditable={editable} suppressContentEditableWarning onBlur={e=>onEdit?.('buttonLabel',e.currentTarget.textContent?.replace(/\s*←\s*$/,'')||'')}>{d.buttonLabel} <ArrowLeft size={14}/></a><a className="sample-link" href="#preview-about">{en?'Learn more':'اعرف المزيد'} <ArrowLeft size={13}/></a></div><div className="sample-proof"><span className="sample-avatars">✦ &nbsp; ✦ &nbsp; ✦</span><span>{en?'Made to inspire':'تجربة مصممة لتلهمك'}</span></div></div><div className="sample-hero-visual"><img src={image} alt={en?'Sample design image':'صورة تجريبية للتصميم'}/><div className="sample-image-note"><span>{en?'Selected collection':'مجموعة مختارة'}</span><b>01 / 04</b></div></div></section>}
function SectionView({s,d,index,editable,onEdit}:{s:Section;d:Design;index:number;editable:boolean;onEdit?:(field:string,value:string)=>void}) {return <section id={index===0?'preview-about':'preview-services'} className={`sample-section section-variant-${s.variant%4} sample-card-${d.cardStyle}`}><div className="section-intro"><span className="sample-kicker">{String(index+1).padStart(2,'0')} / {d.locale==='en'?(sectionKindEnglish[s.kind]||s.kind):s.kind}</span><h2 contentEditable={editable} suppressContentEditableWarning onBlur={e=>onEdit?.(`section:${s.id}:title`,e.currentTarget.textContent||'')}>{s.title}</h2><p contentEditable={editable} suppressContentEditableWarning onBlur={e=>onEdit?.(`section:${s.id}:body`,e.currentTarget.textContent||'')}>{s.body}</p></div><SectionContent s={s} index={index} locale={d.locale} siteType={d.siteType}/></section>}
function Footer({d,editable,onEdit}:{d:Design;editable:boolean;onEdit?:(field:string,value:string)=>void}) {const en=d.locale==='en';return <footer id="preview-contact" className={`sample-footer footer-${d.footer}`} data-name={footerNames[d.footer]}><div><strong contentEditable={editable} suppressContentEditableWarning onBlur={e=>onEdit?.('projectName',e.currentTarget.textContent?.replace(/\.$/,'')||'')}>{d.logoImage&&<img className="sample-logo-image" src={d.logoImage} alt=""/>}{d.projectName || (en?'Your brand':'اسم مشروعك')}<span className="brand-dot">.</span></strong><p contentEditable={editable} suppressContentEditableWarning onBlur={e=>onEdit?.('footerTagline',e.currentTarget.textContent||'')}>{d.footerTagline|| (en?'Experiences to remember.':'نصنع تجارب تبقى في الذاكرة.')}</p>{d.contactEmail&&<p contentEditable={editable} suppressContentEditableWarning onBlur={e=>onEdit?.('contactEmail',e.currentTarget.textContent||'')}>{d.contactEmail}</p>}{d.contactPhone&&<p contentEditable={editable} suppressContentEditableWarning onBlur={e=>onEdit?.('contactPhone',e.currentTarget.textContent||'')}>{d.contactPhone}</p>}</div><div className="sample-footer-links">{d.pages.slice(0,4).map((page,i)=><a key={page+i} href={i===0?'#preview-about':i===d.pages.length-1?'#preview-contact':'#preview-services'}>{page}</a>)}</div><small>© 2026 {d.projectName || 'مشروعك'} — {en?'All rights reserved':'جميع الحقوق محفوظة'}</small></footer>}
export function Preview({design,compact=false,editable=false,onEdit}:{design:Design;compact?:boolean;editable?:boolean;onEdit?:(field:string,value:string)=>void}) {const d=design;const style={'--sample-primary':d.style==='dark'?'#a38bec':d.palette.primary,'--sample-secondary':d.palette.secondary,'--sample-accent':d.palette.accent,'--sample-bg':d.style==='dark'?'#17171d':d.palette.background,'--sample-text':d.style==='dark'?'#f5f2fa':d.palette.text,'--sample-radius':`${d.radius}px`,'--sample-shadow':`${d.shadow/100}`,fontFamily:`${d.font}, Cairo, Arial, sans-serif`,letterSpacing:`${d.letterSpacing}px`,'--heading-scale':d.headingScale,'--heading-weight':d.fontWeight} as React.CSSProperties;return <div className={`sample-site ${compact?'compact':''} motion-${d.motion} design-${d.style}`} dir={d.locale==='ar'?'rtl':'ltr'} style={style}><Nav d={d} editable={editable} onEdit={onEdit}/><Hero d={d} editable={editable} onEdit={onEdit}/>{d.sections.filter(s=>s.visible).map((s,i)=><SectionView key={s.id} s={s} d={d} index={i} editable={editable} onEdit={onEdit}/>)}<Footer d={d} editable={editable} onEdit={onEdit}/></div>}
