'use client';
import { ArrowLeft, Check, Mail, MapPin, Phone, Quote, Star } from 'lucide-react';
import type { Locale, Section } from '@/types/design';

const demoImages = [
  '/preview/store-hero.svg',
  '/preview/product-one.svg',
  '/preview/product-two.svg',
  '/preview/product-three.svg',
];

export function SectionContent({ s, index, locale, siteType }: { s: Section; index: number; locale: Locale; siteType?: string }) {
  const en = locale === 'en';
  const t = (ar: string, english: string) => en ? english : ar;
  const image = s.image || demoImages[(index + 1) % demoImages.length];
  if (/أسئلة|FAQ/.test(s.kind)) return <div className="sample-faq">{[t('كيف يمكننا مساعدتك؟', 'How can we help?'), t('ما الذي يميز تجربتنا؟', 'What makes us different?'), t('كيف أبدأ الآن؟', 'How do I start?')].map((question, i) => <details key={question} open={i === 0}><summary>{question}<span>+</span></summary><p>{s.body}</p></details>)}</div>;
  if (/آراء|شهادات/.test(s.kind)) return <div className="sample-testimonials">{[t('تجربة فاقت توقعاتي، واهتمام واضح بأصغر التفاصيل.', 'A thoughtful experience that exceeded my expectations.'), t('أسلوب عمل احترافي ونتيجة تعبّر عما كنت أبحث عنه.', 'Professional work and a result that feels exactly right.')].map((quote, i) => <blockquote key={i}><Quote size={18}/><p>{quote}</p><div><span>★ ★ ★ ★ ★</span><strong>{i ? t('سارة محمد', 'Sarah M.') : t('أحمد علي', 'Ahmed A.')}</strong></div></blockquote>)}</div>;
  if (/أسعار|الخطط|مقارنة/.test(s.kind)) return <div className="sample-pricing">{[[t('الأساسي', 'Basic'), t('البداية المناسبة', 'A great start'), '29'], [t('المتقدم', 'Growth'), t('الأكثر اختيارًا', 'Most popular'), '59'], [t('الاحترافي', 'Pro'), t('مساحة بلا حدود', 'More room to grow'), '99']].map(([name, subtitle, price], i) => <article key={name} className={i === 1 ? 'featured' : ''}><span>{name}</span><p>{subtitle}</p><strong>{price}<small> OMR / {t('شهريًا', 'month')}</small></strong><ul><li><Check size={12}/> {t('تجربة مخصصة', 'Tailored experience')}</li><li><Check size={12}/> {t('دعم مستمر', 'Ongoing support')}</li><li><Check size={12}/> {t('حلول مرنة', 'Flexible options')}</li></ul><button>{t('ابدأ الآن', 'Get started')} <ArrowLeft size={12}/></button></article>)}</div>;
  if (/تواصل|حجز|مواعيد|المواقع/.test(s.kind)) return <div className="sample-contact"><div><h3>{t('لنتحدث عن فكرتك', 'Let us talk about your idea')}</h3><p>{s.body}</p><span><Phone size={14}/> +968 0000 0000</span><span><Mail size={14}/> hello@example.com</span><span><MapPin size={14}/> {t('عُمان', 'Oman')}</span></div><div className="sample-contact-form"><input placeholder={t('الاسم', 'Name')} readOnly/><input placeholder={t('البريد الإلكتروني', 'Email')} readOnly/><textarea placeholder={t('أخبرنا عن مشروعك', 'Tell us about your project')} readOnly/><button>{t('إرسال رسالة', 'Send message')} <ArrowLeft size={13}/></button></div></div>;
  if (/نبذة|قصة|رسالة|قيمنا/.test(s.kind)) return <div className="sample-story"><img src={image} alt={t('صورة تجريبية للقسم', 'Sample section image')}/><div><span>{t('قصة العلامة', 'Our story')}</span><h3>{t('نؤمن بأن التفاصيل تصنع الأثر.', 'We believe the details make a difference.')}</h3><p>{s.body}</p><a href="#preview-contact">{t('تعرّف أكثر', 'Learn more')} <ArrowLeft size={12}/></a></div></div>;
  if (/دعوة|اشترك|تحميل/.test(s.kind)) return <div className="sample-cta"><span>{t('خطوتك التالية', 'Your next step')}</span><h3>{s.title}</h3><p>{s.body}</p><a href="#preview-contact">{t('ابدأ معنا', 'Get started')} <ArrowLeft size={13}/></a></div>;
  if (/فريق/.test(s.kind)) return <div className="sample-team">{[t('رؤيتنا', 'Vision'), t('إبداعنا', 'Creativity'), t('خبرتنا', 'Expertise')].map((name, i) => <article key={name}><img src={demoImages[(i + 1) % 4]} alt={t('صورة تجريبية', 'Sample image')}/><strong>{name}</strong><small>{t('فريق العمل', 'Our team')}</small></article>)}</div>;
  if (/إحصائ/.test(s.kind)) return <div className="sample-stats">{[['+120', t('مشروع مكتمل', 'Projects completed')], ['98%', t('رضا العملاء', 'Client satisfaction')], ['+8', t('سنوات خبرة', 'Years of experience')]].map(([value, label]) => <div key={label}><strong>{value}</strong><small>{label}</small></div>)}</div>;
  if (/منتج|معرض|أعمال|مدونة|عقارات|مشاريع/.test(s.kind)) return <div className="sample-product-grid">{[0, 1, 2].map(i => <article className="sample-product" key={i}><img src={s.image || demoImages[(index + i + 1) % 4]} alt={t('صورة تجريبية', 'Sample image')}/>{siteType === 'متجر إلكتروني' && <span className="sample-product-badge">{i === 0 ? t('الأكثر طلبًا', 'Bestseller') : i === 1 ? t('جديد', 'New') : t('اختيارنا', 'Editor’s pick')}</span>}<div><b>{siteType === 'متجر إلكتروني' ? [t('حقيبة فورم', 'Form bag'), t('قطعة ستوديو', 'Studio piece'), t('حقيبة أتيليه', 'Atelier bag')][i] : [t('التفاصيل المميزة', 'Featured details'), t('تشكيلة جديدة', 'New collection'), t('اختيارنا لك', 'Picked for you')][i]}</b>{siteType === 'متجر إلكتروني' && <small>{[42, 29, 54][i]} OMR</small>}<span><ArrowLeft size={15}/></span></div></article>)}</div>;
  return <div className="sample-feature-grid">{[['01', t('تصميم مدروس', 'Thoughtful design'), t('كل تفصيل صُمم ليمنحك تجربة أفضل.', 'Every detail creates a better experience.')], ['02', t('جودة يمكنك الوثوق بها', 'Quality you can trust'), t('معايير عالية من البداية حتى النهاية.', 'High standards from start to finish.')], ['03', t('قيمة تدوم', 'Lasting value'), t('حلول عملية تواكب احتياجاتك.', 'Practical solutions for your needs.')]].map(([number, title, body]) => <article key={number}><span>{number}</span><div className="sample-feature-icon"><Star size={18}/></div><h3>{title}</h3><p>{body}</p><ArrowLeft size={16}/></article>)}</div>;
}
